#
# Config for ID generator service
#

# listen addr
addr = "127.0.0.1:6389"
#log_path: /Users/inhere/src
table_mode = "multi" # single, multi
#日志级别
log_level = "debug"
# db table name
table_name = "__idgen_manager"
table_prefix = "gid_key_"
batch_count = 3000

[db]
host = "127.0.0.1"
port = 6033
user = "root"
password = "123456"
db_name = "test"
# db settings
max_idle_conns = 64
